# Generated by Django 3.2.9 on 2021-11-09 02:17

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', banjo.models.StringField(default='')),
                ('email_address', banjo.models.StringField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
